services:
  backend:
    build:
      context: ./vinak
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - vinak-network
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

    frontend:
      build:
        context: ./vinak-frontend
        dockerfile: Dockerfile
      container_name: frontend
      ports:
        - "3000:3000"
      networks:
        - vinak-network
      depends_on:
        - backend
      env_file:
        - .env
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=vinak
      - POSTGRES_PASSWORD=M@haL3M0ND@da5hI
      - POSTGRES_DB=ghedis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vinak-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vinak"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass 3lViN@k0
    volumes:
      - redis_data:/data
    networks:
      - vinak-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "3lViN@k0", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /var/www/html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - vinak-network
    restart: always

  smtp:
    image: boky/postfix
    hostname: mail.vinak.net
    container_name: smtp
    ports:
      - "587:587"
    environment:
      - SMTP_HOSTNAME=mail.vinak.net
      - SMTP_DOMAIN=vinak.net
      - ALLOWED_SENDER_DOMAINS=vinak.net
      - SMTP_RELAY_NETWORKS=-1.0.0.0/0
      - SMTP_SASL_USERS=no-reply:By312£ubk$}P
      - ENABLE_TLS=1
      - TLS_CERT_FILE=/etc/postfix/certs/fullchain.pem
      - TLS_KEY_FILE=/etc/postfix/certs/privkey.pem
    volumes:
      - /etc/letsencrypt/live/mail.vinak.net/fullchain.pem:/etc/postfix/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/mail.vinak.net/privkey.pem:/etc/postfix/certs/privkey.pem:ro
    networks:
      - vinak-network
    restart: always

networks:
  vinak-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: